### ISSUE TITLE
你好,请问第一次访问页面时报这个错是什么问题啊?

### ISSUE THREAD

**Issue by noob9527** [flex1988/Node_blog_V2#2]
11 Jan 05:37:45 - load mongoose model --> blog
11 Jan 05:37:45 - load mongoose model --> log
11 Jan 05:37:45 - load mongoose model --> user
11 Jan 05:37:45 - [TypeError: Cannot read property '**proto**' of undefined]

**Comment by flex1988** [comment]
可能有点年久失修。。

**Comment by flex1988** [comment]
更新代码再试一下

**Comment by noob9527** [comment]
好了 ,谢谢 - -
